apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubescape
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: kubescape-operator
  namespaceSelector:
    matchNames:
      - kubescape
  endpoints:
    - port: metrics
      interval: 200s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubescape-node-agent
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: node-agent
  namespaceSelector:
    matchNames:
      - kubescape
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
